# Generated by Django 4.2.30 on 2026-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('national_admin', 'National Admin'), ('district_officer', 'District Officer'), ('parish_chief', 'Parish Chief'), ('agent', 'Agent'), ('buyer', 'Buyer'), ('farmer', 'Farmer')], max_length=24)),
                ('scope_level', models.CharField(choices=[('national', 'National'), ('district', 'District'), ('subcounty', 'Subcounty'), ('parish', 'Parish')], max_length=16)),
                ('scope_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.AddConstraint(
            model_name='systemuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope_id__isnull', True), ('scope_level', 'national')), models.Q(('scope_id__isnull', False), ('scope_level__in', ['district', 'subcounty', 'parish'])), _connector='OR'), name='user_scope_matches_level'),
        ),
    ]
