# Generated by Django 5.2.17 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(choices=[('national_admin', 'National Admin'), ('district_officer', 'District Officer'), ('subcounty_officer', 'Subcounty Officer'), ('parish_chief', 'Parish Chief'), ('agent', 'Agent'), ('buyer', 'Buyer'), ('farmer', 'Farmer')], max_length=24),
        ),
    ]
