# Generated by Django 4.2.30 on 2026-09-02 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=48, unique=True)),
                ('cycle_weeks', models.PositiveSmallIntegerField(default=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('language', models.CharField(default='lug', max_length=16)),
                ('reach_channel', models.CharField(default='agent', max_length=16)),
                ('nin_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('nin_consent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planting_date', models.DateField()),
                ('variety', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gps_point', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('season_no', models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('year', 'season_no'), name='unique_season'),
        ),
        migrations.AddField(
            model_name='plot',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farmers.farmer'),
        ),
        migrations.AddField(
            model_name='planting',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.crop'),
        ),
        migrations.AddField(
            model_name='planting',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='farmers.plot'),
        ),
        migrations.AddField(
            model_name='planting',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.season'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='geo.village'),
        ),
        migrations.AddConstraint(
            model_name='planting',
            constraint=models.UniqueConstraint(fields=('plot', 'season', 'crop'), name='unique_planting'),
        ),
    ]
