# Generated by Django 4.2.30 on 2026-09-02 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_kg', models.PositiveIntegerField()),
                ('terms', models.CharField(max_length=160)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bags', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('grade', models.CharField(choices=[('grade_1', 'G1'), ('grade_2', 'G2'), ('ungraded', 'Ungraded'), ('reject', 'Reject')], default='ungraded', max_length=10)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('declared_via', models.CharField(default='web', max_length=16)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='farmers.farmer')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('net_amount', models.PositiveIntegerField()),
                ('mm_reference', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.bid')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='market.declaration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_bags', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_lot', to='market.bid')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.crop')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='geo.parish')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='declaration',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='market.lot'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('licence_no', models.CharField(max_length=48, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.buyer'),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='market.lot'),
        ),
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee_minute_ref', models.CharField(max_length=120)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.bid')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.lot')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('lot', 'buyer'), name='one_bid_per_buyer_lot'),
        ),
    ]
