# Generated by Django 4.2.30 on 2026-09-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('org_type', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=64)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(max_length=16)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='farmers.farmer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consent.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=12)),
                ('actor', models.CharField(max_length=120)),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.consent')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.farmer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consent.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
