# Generated by Django 5.2.17 on 2026-09-03 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('op_id', models.CharField(max_length=64, unique=True)),
                ('device_id', models.CharField(max_length=64)),
                ('op_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
