# Generated by Django 4.2.30 on 2026-09-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishSeasonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmers_registered', models.PositiveIntegerField(default=0)),
                ('farmers_active', models.PositiveIntegerField(default=0)),
                ('bags_declared', models.PositiveIntegerField(default=0)),
                ('pct_grade1', models.PositiveSmallIntegerField(default=0)),
                ('avg_price_per_kg', models.PositiveIntegerField(null=True)),
                ('computed_at', models.DateTimeField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crop')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.parish')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parishseasonmetric',
            constraint=models.UniqueConstraint(fields=('parish', 'season', 'crop'), name='unique_parish_metric'),
        ),
    ]
