# Generated by Django 5.2.17 on 2026-09-03 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('farmers', '0002_farmer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_level', models.CharField(choices=[('national', 'National'), ('district', 'District'), ('subcounty', 'Subcounty'), ('parish', 'Parish')], max_length=16)),
                ('scope_id', models.PositiveIntegerField(null=True)),
                ('metric', models.CharField(max_length=48)),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('flat', 'Flat')], max_length=8)),
                ('magnitude', models.DecimalField(decimal_places=2, max_digits=6)),
                ('window_weeks', models.PositiveSmallIntegerField()),
                ('message', models.TextField(max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
