# Generated by Django 5.2.17 on 2026-09-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_trendinsight'),
        ('farmers', '0002_farmer_user'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictSeasonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmers_registered', models.PositiveIntegerField(default=0)),
                ('farmers_active', models.PositiveIntegerField(default=0)),
                ('bags_declared', models.PositiveIntegerField(default=0)),
                ('pct_grade1', models.PositiveSmallIntegerField(default=0)),
                ('avg_price_per_kg', models.PositiveIntegerField(null=True)),
                ('parishes_reporting', models.PositiveIntegerField(default=0)),
                ('rank_national', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.district')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('district', 'season', 'crop'), name='unique_district_metric')],
            },
        ),
        migrations.CreateModel(
            name='NationalSeasonMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmers_registered', models.PositiveIntegerField(default=0)),
                ('farmers_active', models.PositiveIntegerField(default=0)),
                ('bags_declared', models.PositiveIntegerField(default=0)),
                ('pct_grade1', models.PositiveSmallIntegerField(default=0)),
                ('avg_price_per_kg', models.PositiveIntegerField(null=True)),
                ('districts_reporting', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.crop')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('season', 'crop'), name='unique_national_metric')],
            },
        ),
    ]
