# Generated by Django 4.2.30 on 2026-09-02 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agro_zone', models.CharField(blank=True, max_length=32)),
                ('week_from', models.PositiveSmallIntegerField()),
                ('week_to', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=16)),
                ('body', models.TextField(max_length=480)),
                ('source', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('retired', 'Retired')], max_length=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmers.crop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvisoryDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=16)),
                ('fallback_language', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advisory.advisorycontent')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
