# Generated by Django 5.2.17 on 2026-09-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0001_initial'),
        ('analytics', '0003_districtseasonmetric_nationalseasonmetric'),
        ('farmers', '0002_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorydelivery',
            name='trend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='analytics.trendinsight'),
        ),
        migrations.AlterField(
            model_name='advisorydelivery',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advisory.advisorycontent'),
        ),
        migrations.AddConstraint(
            model_name='advisorydelivery',
            constraint=models.CheckConstraint(condition=models.Q(('content__isnull', False), ('trend__isnull', False), _connector='OR'), name='delivery_has_content_or_trend'),
        ),
    ]
